# Unified Configuration for Notion-Hugo Flow Blog
# This file consolidates all configuration settings into a single, clean YAML structure
# Environment variables can override any setting using the pattern: SECTION_SUBSECTION_KEY
# Example: NOTION_API_TOKEN overrides notion.api.token

# =============================================================================
# NOTION INTEGRATION SETTINGS
# =============================================================================
notion:
  api:
    # Notion API token (can be overridden by NOTION_API_TOKEN env var)
    token: "${NOTION_TOKEN:-}"
    # API request timeout in seconds
    timeout: 30
    # Retry configuration
    retry:
      max_attempts: 3
      backoff_factor: 2
      
  # Database and page mounting configuration
  mount:
    # Automatic discovery mode - finds databases from a parent page
    auto_discovery:
      enabled: false
      # Parent page URL for auto-discovery
      parent_page_url: ""
      
    # Manual database configuration (used when auto_discovery is false)
    databases:
      # Posts database configuration
      - database_id: "${NOTION_DATABASE_ID_POSTS:-}"
        target_folder: "posts"
        # Content type for this database
        content_type: "post"
        # Custom property mappings (optional)
        property_mapping:
          title: "Name"
          status: "Status"
          created: "Created"
          tags: "Tags"
          category: "Category"
          
    # Individual pages to sync (optional)
    pages:
      - page_id: "${NOTION_PAGE_ID_ABOUT:-}"
        target_file: "pages/about.md"

  # Synchronization settings
  sync:
    # Sync mode: "smart" (incremental), "full" (complete rebuild)
    mode: "smart"
    # Batch size for processing pages
    batch_size: 10
    # Enable draft synchronization
    include_drafts: false
    # Filter settings
    filters:
      # Only sync published content
      status_filter: ["Published", "Live"]
      # Date range filtering (optional)
      date_range:
        enabled: false
        from: "2020-01-01"
        to: null

# =============================================================================
# HUGO SITE CONFIGURATION
# =============================================================================
hugo:
  # Basic site settings
  site:
    base_url: "https://gunn.kim"
    title: "Exobrain"
    description: "Exobrain in the age of AI"
    language: "en"
    author: "Gunn Kim"
    
  # Theme configuration
  theme:
    name: "PaperMod"
    # Theme-specific parameters
    params:
      env: "production"
      default_theme: "auto"
      show_reading_time: true
      show_share_buttons: true
      show_post_nav_links: true
      show_breadcrumbs: true
      show_code_copy_buttons: true
      show_word_count: true
      show_toc: false
      disable_theme_toggle: false
      
  # Content processing settings
  content:
    # Markdown processing
    markdown:
      renderer: "goldmark"
      # Goldmark settings
      goldmark:
        extensions:
          definition_list: true
          footnote: true
          linkify: true
          strikethrough: true
          table: true
          task_list: true
          typographer: true
        parser:
          auto_heading_id: true
          auto_heading_id_type: "github"
        renderer:
          unsafe: true
          
    # Syntax highlighting
    highlight:
      style: "monokai"
      line_numbers: true
      code_fences: true
      guess_syntax: true
      
    # Math rendering
    math:
      enabled: true
      block_delimiters: ["\\[", "\\]"]
      inline_delimiters: ["\\(", "\\)"]
      copy_tex: true
      mhchem: true
      
  # Menu configuration
  menu:
    main:
      - name: "posts"
        url: "/posts/"
        weight: 5
      - name: "tags"
        url: "/tags/"
        weight: 20
        
  # SEO and analytics
  seo:
    google_analytics:
      site_verification_tag: "G-BQ6CZ7HMQK"
    sitemap:
      change_frequency: "weekly"
      priority: 0.5
      
  # URL and permalink settings
  urls:
    permalinks:
      posts: ":sections/:slug"
      pages: ":slug"
    filename:
      # Filename generation format
      format: "date-title"
      date_format: "%Y-%m-%d"
      # Korean title handling
      korean_title_mode: "slug"

# =============================================================================
# CONTENT PROCESSING SETTINGS
# =============================================================================
content:
  # Image processing
  images:
    optimization: true
    # Image formats to optimize
    formats: ["jpg", "jpeg", "png", "webp"]
    # Maximum image width
    max_width: 1200
    # Quality settings
    quality: 85
    
  # File processing
  files:
    # Allowed file extensions for sync
    allowed_extensions: [".md", ".jpg", ".jpeg", ".png", ".gif", ".svg", ".pdf"]
    # Maximum file size in MB
    max_file_size: 10
    
  # Content validation
  validation:
    # Check for required frontmatter fields
    required_fields: ["title", "date"]
    # Validate markdown syntax
    validate_markdown: true

# =============================================================================
# DEPLOYMENT CONFIGURATION
# =============================================================================
deployment:
  # Deployment strategy
  strategy: "github_actions"
  
  # GitHub Actions configuration
  github_actions:
    # Automatic deployment on sync
    auto_deploy: true
    # Deployment trigger
    trigger: "push"
    # Target branch
    branch: "main"
    # Build environment
    hugo_version: "0.140.0"
    hugo_extended: true
    
  # Synchronization schedule
  schedule:
    # Enable scheduled sync
    enabled: true
    # Cron expression (every 2 hours)
    cron: "0 */2 * * *"
    # Timezone for scheduling
    timezone: "UTC"
    
  # Build settings
  build:
    # Hugo environment
    environment: "production"
    # Enable Git info
    enable_git_info: true
    # Build drafts
    build_drafts: false
    # Build future posts
    build_future: false

# =============================================================================
# DEVELOPMENT SETTINGS
# =============================================================================
development:
  # Local development server
  server:
    port: 1313
    host: "localhost"
    # Auto-reload on changes
    watch: true
    
  # Debug settings
  debug:
    # Enable verbose logging
    verbose: false
    # Log level: debug, info, warn, error
    log_level: "info"
    # Enable performance profiling
    profiling: false
    
  # Docker configuration
  docker:
    # Container settings
    image: "notion-hugo:latest"
    # Port mapping
    ports:
      - "1313:1313"
    # Volume mounts
    volumes:
      - "./:/app"
      - "./.notion-hugo-state.json:/app/.notion-hugo-state.json"

# =============================================================================
# SECURITY AND PRIVACY SETTINGS
# =============================================================================
security:
  # Environment variable handling
  environment_variables:
    # Use environment variables for sensitive data
    use_env_vars: true
    # Validate required environment variables
    validate_env_vars: true
    
  # Logging security
  logging:
    # Mask sensitive information in logs
    mask_sensitive_data: true
    # Mask patterns
    mask_patterns:
      - "ntn_[a-zA-Z0-9]+"  # Notion tokens
      - "[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"  # UUIDs
      
  # Data handling
  data:
    # Backup configuration data
    backup_config: true
    # Encryption for sensitive data (future feature)
    encryption:
      enabled: false
      algorithm: "AES-256-GCM"

# =============================================================================
# FEATURE FLAGS AND EXPERIMENTAL SETTINGS
# =============================================================================
features:
  # Experimental features
  experimental:
    # GraphQL API support
    graphql_api: false
    # Advanced caching
    advanced_caching: false
    # Plugin system
    plugin_system: false
    
  # Legacy feature compatibility
  legacy:
    # Support for old config format
    old_config_support: true
    # Legacy API endpoints
    legacy_api: false

# =============================================================================
# METADATA AND VERSIONING
# =============================================================================
metadata:
  # Configuration metadata
  config_version: "2.0.0"
  # Generated timestamp
  generated_at: "${CONFIG_GENERATED_AT:-}"
  # Generated by
  generated_by: "notion-hugo-cli"
  # Last updated
  last_updated: "${CONFIG_LAST_UPDATED:-}"
  
  # Compatibility information
  compatibility:
    min_notion_hugo_version: "1.0.0"
    hugo_version_range: ">=0.120.0"
    python_version_range: ">=3.8"