mount:
  databases:
  # - database_id: 1b87522e-eb2f-81f6-9cc7-e5e1c0bae02d
  - database_id: 1b47522e-eb2f-8058-8cdb-df406d2b7990 
    target_folder: posts
  manual: true

# 파일명 생성 설정
filename:
  # 파일명 형식: "uuid", "title", "date-title"
  format: "date-title"
  # 날짜 형식: "YYYY-MM-DD"
  date_format: "%Y-%m-%d"
  # 한글 제목 처리: "as-is" (그대로 사용), "slug" (슬러그화만)
  korean_title: "slug"