# Notion-Hugo 통합 설정 파일 (개선된 버전)
# 환경변수 우선, YAML 폴백 방식으로 database_id를 처리합니다.

mount:
  databases:
  # 환경변수 NOTION_DATABASE_ID_POSTS 또는 아래 database_id 사용
  - target_folder: posts
    # database_id는 환경변수가 없을 때만 사용됩니다 (보안상 권장하지 않음)
    database_id: 1b47522e-eb2f-8058-8cdb-df406d2b7990
  
  # 추가 데이터베이스 예시
  # - target_folder: docs
  #   # 환경변수 NOTION_DATABASE_ID_DOCS 또는 아래 database_id 사용
  #   # database_id: your_docs_database_id_here
  
  manual: true

# 파일명 생성 설정
filename:
  # 파일명 형식: "uuid", "title", "date-title"
  format: "date-title"
  # 날짜 형식: "YYYY-MM-DD"
  date_format: "%Y-%m-%d"
  # 한글 제목 처리: "as-is" (그대로 사용), "slug" (슬러그화만)
  korean_title: "slug"

# 보안 설정 가이드:
# 1. 환경변수 사용 (권장):
#    - .env 파일에 NOTION_DATABASE_ID_POSTS=your_database_id 추가
#    - Vercel/GitHub Pages에서 환경변수로 설정
#
# 2. YAML 설정 사용 (비권장):
#    - database_id를 직접 입력하면 Git에 노출됩니다
#    - 개발 환경에서만 사용하고, 배포 시에는 환경변수 사용
#
# 3. 하이브리드 방식 (추천):
#    - 로컬 개발: YAML에 database_id 설정 (.gitignore에 추가)
#    - 배포 환경: 환경변수만 사용
