version: "3"

services:
  notion-hugo:
    build: .
    container_name: notion_hugo
    ports:
      - "1313:1313" # Hugo default port
    volumes:
      - ./:/app # Mount the entire project directory
      - ./.notion-hugo-state.json:/app/.notion-hugo-state.json # Persist metadata state
    environment:
      - HUGO_ENVIRONMENT=development
      - HUGO_ENABLEGITINFO=true
      - NOTION_TOKEN=${NOTION_TOKEN} # Pass Notion API token from host environment
    # Use different commands as needed
    # Basic sync with defaults:
    # command: []
    # Only sync without Hugo build:
    # command: ["--notion-only"]
    # Only Hugo with no sync:
    # command: ["--hugo-only"]
    # Force full sync:
    # command: ["--full-sync"]
