name: ✨ Beta Feature Request
description: Suggest a new feature for v1.0.0 release
title: "[BETA FEATURE] "
labels: ["beta", "enhancement", "v1.0.0"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping shape v1.0.0! 🚀
        
        Your feature suggestions are valuable for prioritizing development.

  - type: input
    id: beta-version
    attributes:
      label: Beta Version
      description: Which beta version are you using?
      value: "v0.9.0-beta"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        Explain the problem you're facing:
        - Current workflow issue
        - Missing functionality
        - Pain point in usage
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution:
        - User interface changes
        - New commands or options
        - Integration suggestions
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Describe any alternative solutions you've considered..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for you?
      options:
        - Critical (Blocking my usage)
        - High (Would significantly improve workflow)
        - Medium (Nice to have improvement)
        - Low (Minor convenience)
    validations:
      required: true

  - type: dropdown
    id: target-version
    attributes:
      label: Target Version
      description: When would you like to see this feature?
      options:
        - v1.0.0 (Essential for release)
        - v1.1.0 (Important for early releases)
        - v1.x.x (Future enhancement)
        - v2.0.0 (Major version feature)
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have technical implementation ideas, share them here
      placeholder: |
        Optional technical details:
        - API changes needed
        - Configuration options
        - Integration points

  - type: checkboxes
    id: terms
    attributes:
      label: Beta Testing Agreement
      options:
        - label: I'm participating in v0.9.0 beta testing
          required: true
        - label: I understand this suggestion will be considered for v1.0.0 planning
          required: true
