defaultMarkdownHandler = 'goldmark'
[goldmark]
[goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'
wrapStandAloneImageWithinParagraph = false
[goldmark.parser.attribute]
block = true
title = true
[goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[goldmark.parser.delimiter]
skipHTML = true
[goldmark.parser.shortcode]
strict = false
[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
noHl = false
style = 'monokai'
tabWidth = 4
[tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
