name: Notion to Hugo Sync

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행 (필요에 따라 조정 가능)
  workflow_dispatch:  # 수동 트리거 허용

# 저장소 권한 설정
permissions:
  contents: write  # 저장소 콘텐츠에 대한 쓰기 권한

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 히스토리 가져오기 (상태 파일 유지에 중요)
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client python-dotenv pyyaml fs tabulate
          
      - name: Run Notion-Hugo sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: python notion_hugo_app.py --notion-only
        
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
          
      - name: Commit changes if any
        if: steps.git-check.outputs.changes > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto-update from Notion [skip ci]"
          git push
